server:
  port: ${SERVER_PORT:8761}

spring:
  security:
    user:
      name: ${EUREKA_USER:eureka}
      password: ${EUREKA_PASSWORD:eureka123}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:eureka}:${EUREKA_PASSWORD:eureka123}@${EUREKA_HOSTNAME:localhost}:${server.port:8761}/eureka/
  server:
    enable-self-preservation: ${ENABLE_SELF_PRESERVATION:false}
    eviction-interval-timer-in-ms: 5000

logging:
  level:
    root: WARN
    com.odc: INFO
    org.springframework: WARN
    org.springframework.cloud: WARN
    com.netflix.discovery: OFF
    reactor.netty: WARN
